version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vehicle_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - '8080:80'
    depends_on:
      - postgres

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/vehicle_db
      PORT: 4000
    ports:
      - '4000:4000'
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      VITE_API_BASE: http://localhost:4000
    ports:
      - '5173:5173'
    depends_on:
      - backend

volumes:
  db-data:
