version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: vehicle_db
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    image: ${DOCKERHUB_USERNAME}/vehicle-management-backend:latest
    restart: always
    env_file:
      - ./backend.env
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/vehicle_db
    ports:
      - '4001:4000'
    depends_on:
      - postgres

  frontend:
    image: ${DOCKERHUB_USERNAME}/vehicle-management-frontend:latest
    restart: always
    ports:
      - '3001:80'

  pgadmin:
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - '8080:80'
    depends_on:
      - postgres

volumes:
  db-data:
