version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: vehicle_db
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    image: ${DOCKERHUB_USERNAME}/vehicle-management-backend:latest
    restart: always
    env_file:
      - ./backend.env
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/vehicle_db
    depends_on:
      - postgres

  frontend:
    image: ${DOCKERHUB_USERNAME}/vehicle-management-frontend:latest
    restart: always

  pgadmin:
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - '8080:80'
    depends_on:
      - postgres

  nginx:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '8000:80'
    depends_on:
      - frontend
      - backend

volumes:
  db-data:
